sudo: required
services:
  - docker

before_install:
  - cd compose/react-app
  - docker build -t compose_react-app-test -f Dockerfile.dev .

script:
  - docker run -e CI=true compose_react-app-test npm test
  - docker build -t compose_react-app-test -f Dockerfile .

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "dockerandkubernatesscourse"
  env: "Dockerandkubernatesscourse-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-349990395107"
  bucket_path: "dockerandkubernatesscourse"
  on:
    branch: main